'use client';

import {
  LayoutDashboard,
  BarChart3,
  ArrowLeftRight,
  FileText,
  Repeat,
  CreditCard,
  MessageSquare,
  Settings,
  HelpCircle,
  LogOut,
  Wallet,
  TrendingUp,
  TrendingDown,
  PiggyBank,
  MoreHorizontal,
  Plus,
  Search,
  Bell,
  ChevronDown,
  ChevronLeft,
  Crown,
  Target,
  Shield,
  Filter,
  ArrowUpRight,
  Send,
  Download,
  Calendar,
  Sun,
  Moon,
  User,
  Home,
  Lock,
  Globe,
  Zap,
  Star,
  Trash2,
  Edit,
  Copy,
  ExternalLink,
  RefreshCw,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Mail,
  Phone,
  MapPin,
  Clock,
  Package,
  Tag,
  Layers,
  Grid,
  List,
  Bookmark,
  Heart,
  Share2,
  Link,
  Image,
  Paperclip,
  Eye,
  EyeOff,
    Users,       
  UserCheck, 
  UserX,
  ShieldCheck,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  home: Home,
  grid: Grid,
  list: List,
  layers: Layers,
  analytics: BarChart3,
  transactions: ArrowLeftRight,
  invoices: FileText,
  recurring: Repeat,
  subscriptions: CreditCard,
  wallet: Wallet,
  expense: TrendingDown,
  savings: PiggyBank,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  piggyBank: PiggyBank,
  feedback: MessageSquare,
  mail: Mail,
  phone: Phone,
  send: Send,
  share: Share2,
  user: User,
  shield: Shield,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  logout: LogOut,
  settings: Settings,
  help: HelpCircle,
  filter: Filter,
  search: Search,
  bell: Bell,
  plus: Plus,
  more: MoreHorizontal,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  crown: Crown,
  target: Target,
  zap: Zap,
  star: Star,
  bookmark: Bookmark,
  heart: Heart,
  tag: Tag,
  download: Download,
  copy: Copy,
  edit: Edit,
  trash: Trash2,
  refresh: RefreshCw,
  externalLink: ExternalLink,
  link: Link,
  arrowUpRight: ArrowUpRight,
  paperclip: Paperclip,
  image: Image,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  info: Info,
  calendar: Calendar,
  clock: Clock,
  sun: Sun,
  moon: Moon,
  globe: Globe,
  mapPin: MapPin,
  package: Package,
  users: Users,
  userActive: UserCheck,
  userInactive: UserX,
  roles: ShieldCheck,
};

export type IconName = keyof typeof Icons;